// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg1lDUiQ-xM3h8-PEw3Jhhy1iYkOqAKw4',
    appId: '1:449991501895:web:78307267f7eaba936fa962',
    messagingSenderId: '449991501895',
    projectId: 'swarm-90059',
    authDomain: 'swarm-90059.firebaseapp.com',
    databaseURL: 'https://swarm-90059.firebaseio.com',
    storageBucket: 'swarm-90059.appspot.com',
    measurementId: 'G-5V8K1CXPW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxBDItoTn3q_PNCCB_j-I9Fmv_qjxtxPA',
    appId: '1:449991501895:android:1086618353136c6e6fa962',
    messagingSenderId: '449991501895',
    projectId: 'swarm-90059',
    databaseURL: 'https://swarm-90059.firebaseio.com',
    storageBucket: 'swarm-90059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQNSjZxMRTeYGoMbxT_2-VeSHUZGwhvU',
    appId: '1:449991501895:ios:97ff37d5fb0413d16fa962',
    messagingSenderId: '449991501895',
    projectId: 'swarm-90059',
    databaseURL: 'https://swarm-90059.firebaseio.com',
    storageBucket: 'swarm-90059.appspot.com',
    androidClientId:
        '449991501895-b8bfb2742dbcblsgdgifr90sbo5pdg2j.apps.googleusercontent.com',
    iosClientId:
        '449991501895-uq8qqd42tr6uvmi5i4dqjk8j3bb4c3l2.apps.googleusercontent.com',
    iosBundleId: 'com.swarmapp.swarm',
  );
}
